//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPAUtOMATION
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement
    {
        public int Id { get; set; }
        public string Announcement1 { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Title { get; set; }
    }
}
