//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPAUtOMATION
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliverable
    {
        public int Id { get; set; }
        public string Phase { get; set; }
        public string Deliverable1 { get; set; }
        public string Document { get; set; }
        public string FYP1 { get; set; }
        public string FYP2 { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
        public string Time_Due { get; set; }
        public string SubmitTo { get; set; }
        public string DocumentPath { get; set; }
        public Nullable<bool> is_Active { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
    }
}
