//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPAUtOMATION
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FYPEntities : DbContext
    {
        public FYPEntities()
            : base("name=FYPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Advisor> Advisors { get; set; }
        public DbSet<Announcement> Announcements { get; set; }
        public DbSet<Document_By_Admin> Document_By_Admin { get; set; }
        public DbSet<group> groups { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Student_Advisor_Request> Student_Advisor_Request { get; set; }
        public DbSet<Student_Document> Student_Document { get; set; }
        public DbSet<Student_Group> Student_Group { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<User_IN_Roles> User_IN_Roles { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
