//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPAUtOMATION
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class FYPEntities : DbContext
    {
        public FYPEntities()
            : base("name=FYPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Advisor> Advisors { get; set; }
        public DbSet<Announcement> Announcements { get; set; }
        public DbSet<Document_By_Admin> Document_By_Admin { get; set; }
        public DbSet<group> groups { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Student_Advisor_Request> Student_Advisor_Request { get; set; }
        public DbSet<Student_Document> Student_Document { get; set; }
        public DbSet<Student_Group> Student_Group { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<User_IN_Roles> User_IN_Roles { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<tblFile> tblFiles { get; set; }
        public DbSet<Student_Request> Student_Request { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<Deliverable> Deliverables { get; set; }
        public DbSet<Grade> Grades { get; set; }
        public DbSet<Project_roadMap> Project_roadMap { get; set; }
        public DbSet<Resource> Resources { get; set; }
        public DbSet<notification> notifications { get; set; }
    
        public virtual ObjectResult<sp_SignUp_Requests_Result> sp_SignUp_Requests()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SignUp_Requests_Result>("sp_SignUp_Requests");
        }
    
        public virtual int sp_Accept_SignUp(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Accept_SignUp", useridParameter);
        }
    }
}
