
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FYPAUtOMATION
{

using System;
    using System.Collections.Generic;
    
public partial class Student_Request
{

    public int ID { get; set; }

    public Nullable<int> Request_From_Id { get; set; }

    public Nullable<int> Request_To_Id { get; set; }

    public Nullable<bool> Is_Active { get; set; }

    public Nullable<System.DateTime> Date_Created { get; set; }

    public Nullable<bool> Is_Accepted { get; set; }

    public Nullable<bool> Is_Rejected { get; set; }

    public Nullable<System.DateTime> Date_Accepeted { get; set; }

}

}
