//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPAUtOMATION
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int ID { get; set; }
        public string Student_Name { get; set; }
        public string Student_Registration_No { get; set; }
        public string Student_Email { get; set; }
        public string Student_Phone { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsPending { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
