//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPAUtOMATION
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Group
    {
        public int Id { get; set; }
        public Nullable<int> Group_Id { get; set; }
        public Nullable<int> Student_1_ID { get; set; }
        public Nullable<int> Student_2_ID { get; set; }
    }
}
