//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPAUtOMATION
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_IN_Roles
    {
        public int Id { get; set; }
        public Nullable<int> Role_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<int> Created_By { get; set; }
    }
}
